.travis.yml
src/memory/GenerationalHeap.cpp
src/memory/GenerationalHeap.h
src/memory/Heap.cpp
src/memory/Heap.h
src/misc/defs.h
src/unitTests/CloneObjectsTest.cpp
src/unitTests/WalkObjectsTest.cpp
src/unitTests/WriteBarrierTest.cpp
src/vm/Universe.cpp
src/vmobjects/VMBlock.h
src/vmobjects/VMClass.h
src/vmobjects/VMDouble.h
src/vmobjects/VMEvaluationPrimitive.h
src/vmobjects/VMFrame.cpp
src/vmobjects/VMFrame.h
src/vmobjects/VMInteger.h
src/vmobjects/VMInvokable.h
src/vmobjects/VMMethod.h
src/vmobjects/VMObject.h
src/vmobjects/VMPrimitive.h
src/vmobjects/VMString.h
src/vmobjects/VMSymbol.h

- use context in VMFrame::SetArgument
- update Travis to use Ubuntu 16.04 reliably
- fix warnings and compilation issues on more modern C++
- use `private_testable:` and `protected_testable:` macros for making class member accessible in cppunit tests
- use VMObjectBase as type in write barrier to avoid cyclic import
- fix memory issue for a preallocated empty string

Fix various minor issues

---

.travis.yml
SOM.xcodeproj/project.pbxproj
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/interpreter/Interpreter.cpp
src/interpreter/Interpreter.h
src/unitTests/BasicInterpreterTests.h
src/unitTests/main.cpp
src/vm/Universe.cpp
src/vm/Universe.h

This PR makes sure that empty blocks return `nil`, see: https://github.com/SOM-st/SOM/pull/54.
In order to test this, I also needed to implement the basic interpreter tests, which apparently hasn't been done before.
To avoid issues with CPPUNIT, I'll switch Travis CI to Ubuntu 20.04, which has cppunit in a version that supports parameterized unit tests.

Fix semantics of empty blocks and implement basic interpreter tests

---

.gitlab-ci.yml
rebench.conf

Signed-off-by: Stefan Marr <git@stefan-marr.de>

Update GitLab setup and ReBench config

---

.github/workflows/ci.yml
SOM.xcodeproj/project.pbxproj
rebench.conf
src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/compiler/Parser.h
src/compiler/SourcecodeCompiler.cpp
src/misc/ExtendedList.h
src/misc/ParseInteger.cpp
src/misc/ParseInteger.h
src/primitives/Double.cpp
src/primitives/Double.h
src/primitives/Integer.cpp
src/primitives/Integer.h
src/primitives/String.cpp
src/primitives/Symbol.cpp
src/primitives/Symbol.h
src/primitives/System.cpp
src/primitives/System.h
src/unitTests/BasicInterpreterTests.h

This PR updates the core-lib to the very latest version and brings SOM++ to the point where it successfully runs SomSom.
This adds:
- missing primitives in Double, Integer, System, incl. `#loadFile:`
- expands support for literal arrays
It also removes the broken inlining of `#ifTrue:`/`#ifFalse:`.
The inlining was not correctly handling shadowing.
So, instead of the broken approach, we should really use the one used in PySOM and TruffleSOM.

Update core-lib to latest version

---

rebench.conf

This adds the rebench.conf bits to run the other benchmarks we regularly run for other SOMs.
The two exceptions are Havlak, which is currently too slow, and Test, which does not pass with the standardized set of expectations, because it doesn't support all the optional features.

Setup other benchmarks regularly run on other SOMs

---

src/compiler/Lexer.cpp
src/compiler/Lexer.h
src/compiler/Parser.cpp
src/compiler/Parser.h
src/vm/Universe.h

This brings the parser a little more in line with PySOM and TruffleSOM.
Adding support for reporting columns in errors is the most relevant change.
Though, the code structure is now also more similar, and the errors are exiting SOM++ to avoid continuing parsing after an error.

Add column tracking for better errors and modernize parser/lexer

---

src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/Disassembler.cpp
src/compiler/Lexer.cpp
src/compiler/Lexer.h
src/compiler/Parser.cpp
src/compiler/Parser.h
src/misc/defs.h
src/unitTests/BasicInterpreterTests.h
src/vmobjects/ObjectFormats.h
src/vmobjects/VMArray.cpp
src/vmobjects/VMArray.h
src/vmobjects/VMObject.cpp
src/vmobjects/VMObject.h

These are some cleanup/simplification changes.
The goal is to eventually be able to run clang-tidy in CI, but I'll only do small cleanups here and there, step wise.

Remove BytecodeGenerator class and start fixing clang-tidy issues

---

src/compiler/MethodGenerationContext.cpp
src/misc/debug.cpp
src/unitTests/CloneObjectsTest.cpp
src/unitTests/WalkObjectsTest.cpp
src/unitTests/WriteBarrierTest.cpp
src/vm/IsValidObject.cpp
src/vm/Universe.cpp
src/vm/Universe.h
src/vmobjects/AbstractObject.h
src/vmobjects/ObjectFormats.h
src/vmobjects/VMClass.cpp
src/vmobjects/VMEvaluationPrimitive.cpp
src/vmobjects/VMEvaluationPrimitive.h
src/vmobjects/VMInvokable.cpp
src/vmobjects/VMInvokable.h
src/vmobjects/VMMethod.cpp
src/vmobjects/VMMethod.h
src/vmobjects/VMPrimitive.cpp
src/vmobjects/VMPrimitive.h
src/vmobjects/VMSymbol.cpp
src/vmobjects/VMSymbol.h

Since SOM changed and does not expose all the details it used to, we do not need to keep the various fields as SOM-level values.
This drastically simplifies things and avoids GC issues.
With the copying and generational GC, we do have to be very careful around cloning objects and walking objects that were already moved.
However, if we use VMIntegers to represent crucial info, that's rather hairy.
So, we just don't do that any longer.

Adapt VMInvokable hierarchy to not be VMObjects

---

SOM.xcodeproj/project.pbxproj
src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/Disassembler.cpp
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/interpreter/Interpreter.cpp
src/interpreter/Interpreter.h
src/interpreter/InterpreterLoop.h
src/interpreter/bytecodes.cpp
src/interpreter/bytecodes.h
src/misc/StringUtil.h
src/unitTests/BytecodeGenerationTest.cpp
src/unitTests/BytecodeGenerationTest.h
src/unitTests/CloneObjectsTest.cpp
src/unitTests/WalkObjectsTest.cpp
src/unitTests/WriteBarrierTest.cpp
src/vm/IsValidObject.cpp
src/vm/Universe.cpp
src/vm/Universe.h
src/vmobjects/VMFrame.h
src/vmobjects/VMMethod.cpp
src/vmobjects/VMMethod.h

This PR uses the infrastructure introduced previously in #32 to implement bytecode-level inlining in the same style as in TruffleSOM and PySOM.
One improvement here is that we remove blocks from the literals, too, which leads in the tests to use more use of the specialized bytecodes.
Generally, the new introduced bytecodes for jumps have all the same length, and exist in two variants, one that only uses one byte, i.e., shorted jumps, and the other that uses both.
This also introduces keeping track of the last 4 bytecodes, which is useful for other optimizations later on, too.

Add inlining of #whileTrue:/#whileFalse:

---

src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/interpreter/bytecodes.cpp
src/unitTests/BytecodeGenerationTest.cpp
src/unitTests/BytecodeGenerationTest.h
src/vmobjects/VMMethod.cpp

This PR adds the inlining for the various messages.
It reduces the median run time by 23% https://rebench.dev/SOMpp/compare/2dc14379c566f40d51791d0e6eca95d743952799..692cc6c47727a7fa76923daf92e0bb8c7d4be3b1

Inline #ifTrue:, #ifFalse:, #ifTrue:ifFalse:, #ifFalse:ifTrue:, #||, #or:, #&&, #and:

---

CMakeLists.txt

This PR enable link-time-based optimizations.
The -O3 is somewhat redundant with "Release", but I threw it in there just for good measures...
https://rebench.dev/SOMpp/compare/7490bff551ff58befee1b4586cf6c2af21975474..b493e7d08ece319387fd8895b245d7aec44dadcc
Change of Run time: median -12% (min. -26%, max. 9%)

Enable LTO

---

rebench.conf
src/interpreter/Interpreter.cpp
src/vmobjects/VMMethod.cpp

This fixes some minor omissions when inlining.

Make sure we use the specialized bytecodes

---

.gitlab-ci.yml
rebench.conf

- adjust benchmark size
- compile more in parallel
- GraphSearch needs memory…

Enable all Generational configurations, but run them on zullie1

---

src/primitives/Array.cpp
src/primitives/Array.h
src/primitives/Block.cpp
src/primitives/Block.h
src/primitives/Double.cpp
src/primitives/Integer.cpp
src/primitives/Method.cpp
src/primitives/Object.cpp
src/primitives/Object.h
src/primitives/Primitive.cpp
src/primitives/String.cpp
src/primitives/String.h
src/primitives/System.cpp
src/primitives/System.h
src/primitivesCore/PrimitiveContainer.cpp
src/primitivesCore/PrimitiveContainer.h
src/primitivesCore/PrimitiveLoader.cpp
src/primitivesCore/PrimitiveLoader.h
src/primitivesCore/Primitives.h
src/unitTests/CloneObjectsTest.cpp
src/vm/IsValidObject.cpp
src/vm/Universe.cpp
src/vmobjects/ObjectFormats.h
src/vmobjects/VMArray.cpp
src/vmobjects/VMArray.h
src/vmobjects/VMClass.cpp
src/vmobjects/VMSafePrimitive.cpp
src/vmobjects/VMSafePrimitive.h
src/vmobjects/VMSymbol.cpp
src/vmobjects/VMSymbol.h

Also introduce ternary safe primitives and use them where possible.
Lowered primitives:
- Array>>#copy
- Double #<=, #>, #>=, #<>, #~=, #min:, #max:
- Integer #<=, #>, #>=, #<>, #~=, #min:, #max:, #abs, #to:
- String>>#charAt:

Lower various operations to be primitives, matching PySOM

---

src/unitTests/CloneObjectsTest.cpp
src/unitTests/WalkObjectsTest.cpp
src/vm/Universe.cpp
src/vmobjects/ObjectFormats.h
src/vmobjects/VMClass.cpp
src/vmobjects/VMClass.h
src/vmobjects/VMEvaluationPrimitive.cpp
src/vmobjects/VMEvaluationPrimitive.h
src/vmobjects/VMPrimitive.h
src/vmobjects/VMSafePrimitive.h

I am not quite sure what the point of `EvaluationRoutine` is.
I suspect it was to make sure primitives can be handled uniformly with the block evaluation.
But that seems not very beneficial, and makes the code more complex.
So, this PR removes `EvaluationRoutine`.

Remove EvaluationRoutine to simplify block evaluation handling

---

src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/interpreter/InterpreterLoop.h
src/interpreter/bytecodes.cpp
src/interpreter/bytecodes.h
src/unitTests/BytecodeGenerationTest.cpp

The main motivation for this PR is to simplify bytecode sequences, remove a bit of cruft, to make it easier to recognize setters as trivial methods.
Though, this also gives a bit of a performance benefit, especially on micro benchmarks.
The PR also adds more of the unusual infrastructure we have to deal with bytecodes.
https://rebench.dev/SOMpp/compare/dc902fb54bd693ccc02f3cbd4f1cedc2ae802649..e33d58323d14ab2e3f5befc7c37218df9c3cbab1
Run time: median -1% (min. -46%, max. 14%)

Add RETURN_SELF and optimize the DUP, POP_X, POP sequences

---

src/Main.cpp
src/compiler/Lexer.cpp
src/compiler/MethodGenerationContext.cpp
src/compiler/Parser.cpp
src/interpreter/Interpreter.cpp
src/memory/CopyingHeap.cpp
src/memory/DebugCopyingHeap.cpp
src/memory/GenerationalHeap.cpp
src/memory/MarkSweepHeap.cpp
src/primitives/Double.cpp
src/primitives/System.cpp
src/vm/Print.cpp
src/vm/Print.h
src/vm/Shell.cpp
src/vm/Universe.cpp
src/vm/Universe.h
src/vmobjects/VMArray.cpp
src/vmobjects/VMClass.cpp
src/vmobjects/VMEvaluationPrimitive.cpp
src/vmobjects/VMFrame.cpp
src/vmobjects/VMFrame.h
src/vmobjects/VMInvokable.cpp
src/vmobjects/VMMethod.cpp
src/vmobjects/VMMethod.h
src/vmobjects/VMPrimitive.cpp
src/vmobjects/VMSafePrimitive.cpp
src/vmobjects/VMTrivialMethod.cpp

- make RemainingStackSize inlinable
- mark an out-of-bounds check as unlikely
- make ErrorExit and Quit non-inlinable
This seem to give a surprising amount of speed: median -3% (min. -25%, max. 10%)
https://rebench.dev/SOMpp/compare/4ba47cfe11c5e5b4d5379c36de923faf601ffc93..8866a58999526c54a50fc5d4e4c948ee94176a89

Micro optimizations of interpreter loop

---

src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/interpreter/Interpreter.cpp
src/interpreter/Interpreter.h
src/interpreter/InterpreterLoop.h
src/interpreter/bytecodes.cpp
src/interpreter/bytecodes.h
src/unitTests/BytecodeGenerationTest.cpp
src/unitTests/BytecodeGenerationTest.h
src/unitTests/TestWithParsing.cpp
src/vmobjects/VMMethod.cpp

Performance is a bit unclear whether this is noice: median -3% (min. -25%, max. 10%)
https://rebench.dev/SOMpp/compare/e1feaf1782d3b1f51263a5a52ddf7898d7403812..57cae1ae59d0cbfadf8c5ee9af41ae0dd1ed01c3

Implement RETURN_FIELD_* bytecodes and port more of the tests

---

src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/Disassembler.cpp
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/compiler/Parser.h
src/interpreter/Interpreter.cpp
src/interpreter/Interpreter.h
src/interpreter/InterpreterLoop.h
src/interpreter/bytecodes.cpp
src/interpreter/bytecodes.h
src/unitTests/BytecodeGenerationTest.cpp
src/unitTests/BytecodeGenerationTest.h
src/unitTests/TestWithParsing.cpp
src/unitTests/TestWithParsing.h
src/vm/Symbols.cpp
src/vm/Symbols.h
src/vmobjects/VMMethod.cpp

And a few other improvements.
Performance: median -4% (min. -23%, max. 25%)
https://rebench.dev/SOMpp/compare/ed7f335ff398a09cec92358edd14aa3a38f7c32a..9dd7227ebac802b1be54023e04e677654479d940

Implement DEC, INC_FIELD, INC_FIELD_PUSH

---

src/unitTests/WalkObjectsTest.cpp
src/unitTests/WriteBarrierTest.cpp
src/vm/IsValidObject.cpp
src/vm/Universe.cpp
src/vmobjects/VMFrame.cpp
src/vmobjects/VMFrame.h

- move most bits to the constructor
- do not initialize arguments with nil since they will be set during the call

Optimize VMFrame Creation

---

src/unitTests/CloneObjectsTest.cpp
src/vmobjects/ObjectFormats.h
src/vmobjects/VMArray.cpp
src/vmobjects/VMArray.h
src/vmobjects/VMFrame.cpp
src/vmobjects/VMFrame.h
src/vmobjects/VMInvokable.cpp
src/vmobjects/VMInvokable.h
src/vmobjects/VMObject.cpp
src/vmobjects/VMObject.h
src/vmobjects/VMString.cpp
src/vmobjects/VMString.h
src/vmobjects/VMSymbol.cpp
src/vmobjects/VMSymbol.h

AbstractVMObject is simpler than VMObject, avoids some fields and other bits.
The rest is moving some bits to headers to allow the compilers to inline.

Make VMFrame an AbstractVMObject and allow for more inlining

---

src/primitives/String.cpp
src/vmobjects/VMArray.cpp
src/vmobjects/VMArray.h
src/vmobjects/VMString.cpp
src/vmobjects/VMString.h

median 0% (min. -15%, max. 26%)
https://rebench.dev/SOMpp/compare/8a8617cb121513096e3b87244c8899ac6251be2c..1e17f763dd1f34d0f99c14eb403d0eedd6e27452

Avoid nil-ing VMArray twice and improve strEqual and VMString inlining

---

.gitlab-ci.yml

This updates the ReBench and GitLab CI setup to work on the latest version of ReBench.

Fix filtering of ReBench runs on GitLab

---

src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/Disassembler.cpp
src/compiler/Disassembler.h
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/interpreter/InterpreterLoop.h
src/interpreter/bytecodes.cpp
src/interpreter/bytecodes.h
src/unitTests/BytecodeGenerationTest.cpp
src/vmobjects/VMEvaluationPrimitive.cpp
src/vmobjects/VMEvaluationPrimitive.h
src/vmobjects/VMFrame.h
src/vmobjects/VMInvokable.h
src/vmobjects/VMMethod.cpp
src/vmobjects/VMMethod.h
src/vmobjects/VMPrimitive.cpp
src/vmobjects/VMPrimitive.h
src/vmobjects/VMSafePrimitive.cpp
src/vmobjects/VMSafePrimitive.h
src/vmobjects/VMTrivialMethod.cpp
src/vmobjects/VMTrivialMethod.h

This PR uses the existing support for inlining of `ifTrue:` etc to also support `ifNil:` etc.
The inlining logic is mostly unchanged, just generalized to support the different bytecodes.
The new bytecodes are, incl. JUMP2 omitted here:
```
BC_JUMP_ON_NOT_NIL_POP     50
BC_JUMP_ON_NIL_POP         51
BC_JUMP_ON_NOT_NIL_TOP_TOP 52
BC_JUMP_ON_NIL_TOP_TOP     53
```
The bytecodes check for `nil` and may keep the top element (`TOP_TOP` to be read as top is set to top), or pop it on success.
The PR also resolves some lint issues and improve the disassembler.
When integers are not tagged, BC_INC now needs a GC check, to avoid running out of memory on the `IfNil` benchmark.

Implement inlining for #ifNil:*, #ifNotNil:* selectors

---

src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/interpreter/bytecodes.cpp
src/misc/debug.cpp
src/misc/debug.h
src/unitTests/BytecodeGenerationTest.cpp
src/unitTests/BytecodeGenerationTest.h
src/unitTests/TestWithParsing.cpp
src/unitTests/TestWithParsing.h
src/vmobjects/VMFrame.h
src/vmobjects/VMMethod.cpp
src/vmobjects/VMMethod.h

The inlining logic did not yet account for the block argument of `#to:do:` being turned into a local variable.
This PR uses the existing lexical scope and mgenc to look up the matching new version of the previous argument.
It also adds handling for `DUP_SECOND` in `AdaptAfterOuterInlined` and fixes the adapting of `INC_FIELD_PUSH` and `INC_FIELD` which do not have explicit context arguments.

Fix handling of inlined args and some bytecodes

---

LICENSE
README.md

Currently the build instruction will generate a debug build, instead of the release build. This can easily mislead readers who wants to use or benchmark SOM++. This diff changed the build instructions to do a release build instead. Also removed the obsoleted description about CSOM "make debug" (this won't work for SOM++: the build flavor must be passed to CMake instead).

The build instructions should do a release build, not debug build

---

src/interpreter/Interpreter.h
src/primitives/Block.cpp
src/primitives/Block.h
src/primitives/Method.cpp
src/primitives/Method.h
src/primitives/Primitive.cpp
src/primitives/Primitive.h
src/vmobjects/VMFrame.cpp
src/vmobjects/VMFrame.h

This PR restores the restart primitive on blocks so that `#whileTrue:` and `#whileFalse:` work correctly for blocks that were not inlined.
Issue reported by @sillycross. Thanks.
Needs https://github.com/SOM-st/SOM/pull/125 to be merged to update core-lib to a merged version.

Restore block restart

---

src/compiler/BytecodeGenerator.cpp
src/compiler/BytecodeGenerator.h
src/compiler/MethodGenerationContext.cpp
src/compiler/MethodGenerationContext.h
src/compiler/Parser.cpp
src/compiler/Parser.h
src/vmobjects/VMEvaluationPrimitive.cpp
src/vmobjects/VMEvaluationPrimitive.h
src/vmobjects/VMInvokable.h
src/vmobjects/VMMethod.cpp
src/vmobjects/VMMethod.h
src/vmobjects/VMPrimitive.cpp
src/vmobjects/VMPrimitive.h
src/vmobjects/VMSafePrimitive.cpp
src/vmobjects/VMSafePrimitive.h
src/vmobjects/VMTrivialMethod.cpp
src/vmobjects/VMTrivialMethod.h

This PR introduces `ParserError()` calls to report when code goes over certain limits.
For instance, we can currently only support 256 literal values, because the literal index is encoded as an 8bit number. The same restriction applies for field indexes etc.

Add parser errors to make sure we do not generate wrong bytecodes

---

rebench.conf

This PR updates the core-lib to the latest version, which includes a few tests and two benchmarks. The benchmarks are added to the benchmarking setup.

Update core-lib and add Knapsack and VectorBenchmark to rebench.conf

---

src/lib/InfInt.h
src/primitives/Integer.cpp
src/unitTests/InfIntTests.cpp
src/unitTests/InfIntTests.h
src/vm/IsValidObject.cpp
src/vm/Universe.cpp
src/vm/Universe.h
src/vmobjects/ObjectFormats.h
src/vmobjects/VMBigInteger.h

This is the follow up to #74 and makes sure that we don't have VMBigInteger objects that could just be tagged ints.
The PR also fixes a typing issue with the relevant macros and has a few other minor improvements.

Make sure we don't allocate VMBigInteger objects for values fitting into the small int range
